Repository gbowne1/random_c_cpp_programs, pull requests merged in 2024-01, with the labels that each got.

#3 righttrinangle.cpp: Allow the user to choose the unit of measurement
  cpp_programs/righttriangle.cpp
Labels: enhancement, help wanted, good first issue

#8 Fix issue #2: include user input on lowpassfil.c
  c_programs/lowpassfil.c
Labels: bug, enhancement, help wanted, good first issue

#11 GradeBook data structures, file examples and CMake
  cpp_programs/gradebook/CMakeLists.txt
  cpp_programs/gradebook/assignmentdata.csv
  cpp_programs/gradebook/classdata.csv
  cpp_programs/gradebook/dataframe.cpp
  cpp_programs/gradebook/dataframe.h
  cpp_programs/gradebook/gradebook.cpp
  cpp_programs/gradebook/gradebook.h
  cpp_programs/gradebook/grades.csv
  cpp_programs/gradebook/studentdata.csv
  cpp_programs/gradebook/teacherdata.csv
Labels: bug, enhancement, help wanted, good first issue

#14 Adding new programs and fixing CMakeLists.txt version
  .vscode/settings.json
  c_programs/resistance.c
  cpp_programs/gradebook/CMakeLists.txt
  cpp_programs/longdiv.cpp
Labels: bug, documentation, enhancement, help wanted, good first issue, question

#13 DataFrame print table, Main menu and CMake copy CSV files to build directory
  cpp_programs/gradebook/build/assignmentdata.csv
  cpp_programs/gradebook/build/classdata.csv
  cpp_programs/gradebook/build/gradebook
  cpp_programs/gradebook/build/grades.csv
  cpp_programs/gradebook/build/studentdata.csv
  cpp_programs/gradebook/build/teacherdata.csv
Labels: enhancement, help wanted, good first issue

#15 Shipping actual updates from last pull request
  .gitignore
  cpp_programs/gradebook.cpp
  cpp_programs/gradebook.h
  cpp_programs/gradebook/CMakeLists.txt
  cpp_programs/gradebook/build/assignmentdata.csv
  cpp_programs/gradebook/build/classdata.csv
  cpp_programs/gradebook/build/gradebook
  cpp_programs/gradebook/build/grades.csv
  cpp_programs/gradebook/build/studentdata.csv
  cpp_programs/gradebook/build/teacherdata.csv
  cpp_programs/gradebook/dataframe.cpp
  cpp_programs/gradebook/dataframe.h
  cpp_programs/gradebook/gradebook.cpp
  cpp_programs/gradebook/gradebook.h
Labels: enhancement, help wanted, good first issue

#17 Move CSV files to assets folder + primitive permissions system
  .gitignore
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  cpp_programs/gradebook/CMakeLists.txt
  cpp_programs/gradebook/assets/assignmentdata.csv
  cpp_programs/gradebook/assets/classdata.csv
  cpp_programs/gradebook/assets/grades.csv
  cpp_programs/gradebook/assets/studentdata.csv
  cpp_programs/gradebook/assets/teacherdata.csv
  cpp_programs/gradebook/permissions.cpp
  cpp_programs/gradebook/permissions.h
Labels: enhancement, help wanted

#22 Add '_CRT_SECURE_NO_WARNINGS' definition to matrixmath.c
  c_programs/matrixmath.c
Labels: bug, enhancement, help wanted

#25 Add kelvin temperature converter to tempconvert.c
  c_programs/tempconvert.c
Labels: enhancement, help wanted, good first issue

#26 Add width and height to winsize.cpp
  cpp_programs/winsize.cpp
Labels: enhancement
